### PR TITLE
Only one deploy for non-config leaf certs

### PR DESCRIPTION
**Pull request by rcarl94**
I think it might just be some good old copy pasta.

### CODE REVIEW

**Comment by paigecalvert** [comment]
Thanks @rcarl94! I notice that you PR'd version 2.9. Should this also appear on all other versions of this doc?

**Comment by rcarl94** [comment]
Yep!

**Comment by paigecalvert** [comment]
Thanks! As it happens, we had a story in the backlog to edit this procedure. The updates we made also address the issue that you pointed out, so I'm going to close this PR. But thank you again for submitting! 

Here's the updated procedure. (You can also see it live at https://docs.pivotal.io/platform/2-9/security/pcf-infrastructure/api-cert-rotation.html#regenerate)
Screen Shot 2020-07-22 at 3 37 00 PM

**Comment by rcarl94** [comment]
Thanks, Paige!

**Pull request closed without merging**
