### PR TITLE
add jmx-bridge information

### PR DESCRIPTION
**Pull request by jtarchie**
Signed-off-by: Ben Fuller <bfuller@pivotal.io>

### CODE REVIEW

**Comment by seviet** [comment]
thank you @jtarchie!

**Comment by seviet** [comment]
@jtarchie oops-- one question-- what version(s) of JMX Bridge do these flows cover?

**Comment by jtarchie** [comment]
PCF JMX Bridge 1.9+ -- for 1.11 to 2.x.

**Comment by seviet** [comment]
thanks!

**Pull request merged**
