### PR TITLE
Update and reorganize instance-cred documentation

### PR DESCRIPTION
**Pull request by emalm**
* Add details about validity period and periodic regeneration of credentials
* Move up environment variable information
* Clarify and consolidate information about the issuing CA
* Clarify that certificate file may contain intermediate CAs in a certificate chain

Thanks to @ljarzynski for the editing discussion earlier today. I'm definitely looking for more feedback on these changes before they are merged, and am happy to discuss here or via other channels.

### CODE REVIEW

**Comment by ljarzynski** [comment]
Thanks @emalm! I'll be taking a look at this soon. If not before EOD, then Tues.

**Comment by emalm** [comment]
Thanks @ljarzynski ! Happy to pair on it with you, too.

**Comment by ljarzynski** [comment]
@emalm I refined the presentation a little further and wanted to merge it just to make the info available. But still open and ready to incorporate any feedback you may have!

**Comment by emalm** [comment]
Thanks, @ljarzynski ! The tabular reorganization looks great.

For the "issuing authority" section, I think it would make sense to separate out more explicitly the issuance of the certs from how the platform is configured to trust the certs automatically. That the certificates are issued from that separate root CA dedicated to instance-identity credentials is an intrinsic property of the certificates themselves: any party that wants to trust them must then trust the certificate for that root CA. The configuration of the platform (app instance containers, gorouters) to trust that root CA is then a separate matter that depends on the issuance of the certs.

Put another way, I see there being two separate questions to ask, namely, "How does my client or server trust the certificate that this app presents?" and "How is the platform configured to trust these apps' certificates automatically?", and the respective answers being roughly, "It should trust this root CA certificate", and "We installed that root CA certificate in the trust stores for containers and for certain components".

Anyway, happy to discuss that or any other revisions in person!

Thanks again,
Eric

**Pull request merged**
