### PR TITLE
Making Step 3 as NOT Optional: Rotate Configurable Leaf Certificates

### PR DESCRIPTION
**Pull request by vibhas**
Making Step 3: Rotate Configurable Leaf Certificates as NOT optional.

### CODE REVIEW

**Comment by jncd** [comment]
Hi @vibhas 
I merged your PR. However, I don't truly follow what you're trying to say... 
"should" is such an ambiguous verb in tech writing.  Does it mean you _must_ or does it mean that you _should_ but you _don't really have to_? 

The procedure that it links to is also a bit confusing because the intro doesn't mention the configurable leaf certs:
> This procedure uses the Ops Manager API to rotate the Ops Manager root CA and non-configurable leaf certificates. 

However, the warning says I have to do _all_ the steps and step 3 says rotate the configurable leaf certificates.

> Warning: You must complete these steps in the exact order specified. Otherwise, you may damage your deployment.

...

> 3. Rotate configurable leaf certificates. For more information, see Rotate Configurable Leaf Certificates.

**Comment by jncd** [comment]
My suggestion would be to edit the doc as shown in the blue highlights. Let me know what you think.
Screen Shot 2020-03-27 at 1 55 32 PM
Screen Shot 2020-03-27 at 1 56 03 PM

**Comment by vibhas** [comment]
Hi @jncd , thanks a lot for your useful feedback!
Your suggestions make sense and look good to me. But I will also like to get @ystros opinion on this before you make those changes.

**Comment by jncd** [comment]
Hi @vibhas 
Good idea! When we hear back from @ystros I'll make changes if/as you see fit.

**Comment by ystros** [comment]
Hi @jncd, the blue highlighted sections more or less make sense to me. One nuance of this documentation update is that it is only required if the customer has either:
1. Used the "Generate RSA Certificate" feature within the Ops Manager UI
or
2. Has provided their own custom certificates that are about to expire

In this regard, saying that the procedure rotates "all configurable" certs could be confusing, as it is only required under certain circumstances. But that may be hard to encapsulate in a summary sentence.

These documentation changes should be backported to essentially all supported versions of Ops Manager, as they are not 2.9 specific.

**Pull request merged**
